### ISSUE TITLE
大哥帮我回答个问题啊，谢谢你啊

### ISSUE THREAD

**Issue by Jerry-cloud-source** [Aizener/admin-permission#1]
sessionStorage.getItem('v-user') && initDynamicRouter()
你写的这个代码是什么意思的吖，为什么有了这句代码刷新页面路由数据就不会消失了，为什么呢

**Comment by Aizener** [comment]
我默许你已经知道`sessionStorage`的用法了哈，可能你是对代码的流程不懂，这句代码：`sessionStorage.getItem('v-user') && initDynamicRouter()`其实作用就是一个功能：**通过判断是否有用户，来重新渲染菜单**，至于为什么要这样做，是因为：

1. 刚加载页面时，判断`sessionStorage`里面是否有`v-user`这个值，有的话就初始化路由，为什么要这样做的话，是因为：

```js
this.setUser(res.data)
initDynamicRouter()
sessionStorage.setItem('v-user', JSON.stringify(res.data))
sessionStorage.setItem('v-encryp', encodeURIComponent(JSON.stringify(res.data)))
this.$router.push('/')
```

我们初始化路由是在第一次登录的时候通过`initDynamicRouter`方法渲染的，自然的这个时候也缓存了用户信息。

2. 但是，当下一次刷新的时候，因为用户信息还在，所以不会走登录这个流程；所以，在判断已登录时，就执行`initDynamicRouter`进行菜单的初始化。

> 加油！:thumbsup:

**Comment by Jerry-cloud-source** [comment]
懂了，谢谢了，还有这个 if (sessionStorage.getItem('user')) { dynamicRoutes() } 为什么可以简写成 sessionStorage.getItem('user') && dynamicRoutes() 呢，这是什么语法啊

**Comment by Aizener** [comment]
`&&`这个叫做**逻辑与**；其实一般是用于判断用的，但是也可以像我那样用。
`表达式1 && 表达式2` 如果表达式1为`true`就执行表达式2；切记，是一个表达式。
如果想在逻辑与的右边执行语句的话，可以加括号：
`表达式 && (语句)`

**Comment by Jerry-cloud-source** [comment]
大哥，我做自定义指令报这个错怎么解决呢，我是按照视频中来写的，为啥那个老师的没有报错呢
`import Vue from 'vue'
import router from '@/router'
Vue.directive('permission', {
  inserted (el, binding) {
    // console.log(el)
    console.log(binding)
    const action = binding.value.action
    // 判断，在当前路由所对应的组件中，如何判断用户是否具备 action 权限
    console.log(action)
    console.log(router.currentRoute.meta)
    if (router.currentRoute.meta.index0f(action) === -1) {
        el.parentNode.removeChild(el)
    }
  }
})`

报错信息 Error in directive permission inserted hook: "TypeError: _router__WEBPACK_IMPORTED_MODULE_1__.default.currentRoute.meta.index0f is not a function"
