### ISSUE TITLE
大哥，帮我再解决个问题吧，搞了很久都不知道解决

### ISSUE THREAD

**Issue by Jerry-cloud-source** [Aizener/admin-permission#2]
大哥，我做自定义指令报这个错怎么解决呢，我是按照视频中来写的，为啥那个老师的没有报错呢
import Vue from 'vue' import router from '@/router' Vue.directive('permission', { inserted (el, binding) { // console.log(el) console.log(binding) const action = binding.value.action // 判断，在当前路由所对应的组件中，如何判断用户是否具备 action 权限 console.log(action) console.log(router.currentRoute.meta) if (router.currentRoute.meta.index0f(action) === -1) { el.parentNode.removeChild(el) } } })

报错信息 Error in directive permission inserted hook: "TypeError: router__WEBPACK_IMPORTED_MODULE_1_.default.currentRoute.meta.index0f is not a function"

**Comment by gutrse3321** [comment]
大哥现在在绝赞加班ing...
